---
- name: Declare internal variables
  ansible.builtin.set_fact:
    __app_name: sample-app-web-server

- name: Remove quadlet file
  ansible.builtin.file:
    path: '{{ setup_sample_app__quadlet_dir }}/{{ __app_name }}.container'
    state: absent

- name: Stop systemd service
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: stopped
    name: '{{ __app_name }}'
...
