---
- name: Template quadlet files
  ansible.builtin.template:
    src: sample-app-web-server.container.j2
    dest: '{{quadlet_dir}}/sample-app-web-server.container'
    owner: root
    group: wheel
    mode: '0644'

- ansible.builtin.shell:
    cmd: systemctl daemon-reload

- ansible.builtin.shell:
    cmd: 'systemctl start sample-app-web-server'
...
