---
- name: Deploy sample-app to vm
  become: true
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for host to become reachable
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300
  roles:
    - setup_podman
    - setup_sample_app

- name: Print host ips to the console
  hosts: all
  strategy: linear
  tasks:
    - name: Print # noqa: run-once[task]
      ansible.builtin.debug:
        msg: 'Application available at:'
      run_once: true

    - name: Print
      ansible.builtin.debug:
        msg: 'http://{{ ansible_host }}'
...
