---
argument_specs:
  main:
    short_description: Deploys sample-app as a Podman Quadlet on the target machine
    options:
      setup_sample_app__quadlet_dir:
        type: "str"
        default: "/etc/containers/systemd/"
      setup_sample_app__web_server_image_url:
        type: "str"
        required: true
      setup_sample_app__web_server_port:
        type: "int"
        default: 80
...
