name: Main

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Ansible, Terraform, and Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: opentofu/setup-opentofu@v1
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-node@v4
        with:
          node-version:
      - run: make install
      - run: make lint

